# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grapevine.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grapevine.proto',
  package='grapevine',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fgrapevine.proto\x12\tgrapevine\"X\n\x07Message\x12\x0b\n\x03raw\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\x03\x12\x0c\n\x04urls\x18\x05 \x03(\t\"\x87\x01\n\x0e\x43lassification\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12\x12\n\nprediction\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x01\x12\r\n\x05model\x18\x04 \x01(\t\x12\x0f\n\x07version\x18\x05 \x01(\t\x12\x1d\n\x04meta\x18\x06 \x01(\x0b\x32\x0f.grapevine.Meta\"\x88\x01\n\x04Meta\x12&\n\tsentences\x18\x01 \x03(\x0b\x32\x13.grapevine.Sentence\x12:\n\x13spamassassin_report\x18\x02 \x01(\x0b\x32\x1d.grapevine.SpamAssassinReport\x12\x1c\n\x04\x61sks\x18\x03 \x03(\x0b\x32\x0e.grapevine.Ask\"F\n\x08Sentence\x12\x16\n\x0esentence_score\x18\x01 \x01(\x01\x12\x13\n\x0bword_scores\x18\x02 \x03(\x01\x12\r\n\x05words\x18\x03 \x03(\t\"\x81\x01\n\x12SpamAssassinReport\x12\x35\n\x11quantitative_hits\x18\x01 \x03(\x0b\x32\x1a.grapevine.SpamAssassinHit\x12\x34\n\x10qualitative_hits\x18\x02 \x03(\x0b\x32\x1a.grapevine.SpamAssassinHit\"E\n\x0fSpamAssassinHit\x12\r\n\x05score\x18\x01 \x01(\x01\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"y\n\x03\x41sk\x12\x10\n\x08sentence\x18\x01 \x01(\t\x12\x14\n\x0craw_sentence\x18\x02 \x01(\t\x12\x11\n\tstart_idx\x18\x03 \x01(\x05\x12\x0f\n\x07\x65nd_idx\x18\x04 \x01(\x05\x12\x12\n\nprediction\x18\x05 \x01(\t\x12\x12\n\nconfidence\x18\x06 \x01(\x01\"]\n\nExtraction\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x01\x12\r\n\x05model\x18\x04 \x01(\t\x12\x0f\n\x07version\x18\x05 \x01(\t2I\n\nClassifier\x12;\n\x08\x43lassify\x12\x12.grapevine.Message\x1a\x19.grapevine.Classification\"\x00\x32\x43\n\tExtractor\x12\x36\n\x07\x45xtract\x12\x12.grapevine.Message\x1a\x15.grapevine.Extraction\"\x00\x62\x06proto3')
)




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='grapevine.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='raw', full_name='grapevine.Message.raw', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='grapevine.Message.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='language', full_name='grapevine.Message.language', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='grapevine.Message.created_at', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='urls', full_name='grapevine.Message.urls', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=118,
)


_CLASSIFICATION = _descriptor.Descriptor(
  name='Classification',
  full_name='grapevine.Classification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='domain', full_name='grapevine.Classification.domain', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prediction', full_name='grapevine.Classification.prediction', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='grapevine.Classification.confidence', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='grapevine.Classification.model', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='grapevine.Classification.version', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meta', full_name='grapevine.Classification.meta', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=256,
)


_META = _descriptor.Descriptor(
  name='Meta',
  full_name='grapevine.Meta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentences', full_name='grapevine.Meta.sentences', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spamassassin_report', full_name='grapevine.Meta.spamassassin_report', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='asks', full_name='grapevine.Meta.asks', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=395,
)


_SENTENCE = _descriptor.Descriptor(
  name='Sentence',
  full_name='grapevine.Sentence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentence_score', full_name='grapevine.Sentence.sentence_score', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='word_scores', full_name='grapevine.Sentence.word_scores', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='words', full_name='grapevine.Sentence.words', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=467,
)


_SPAMASSASSINREPORT = _descriptor.Descriptor(
  name='SpamAssassinReport',
  full_name='grapevine.SpamAssassinReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quantitative_hits', full_name='grapevine.SpamAssassinReport.quantitative_hits', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qualitative_hits', full_name='grapevine.SpamAssassinReport.qualitative_hits', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=470,
  serialized_end=599,
)


_SPAMASSASSINHIT = _descriptor.Descriptor(
  name='SpamAssassinHit',
  full_name='grapevine.SpamAssassinHit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='grapevine.SpamAssassinHit.score', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='grapevine.SpamAssassinHit.symbol', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='grapevine.SpamAssassinHit.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=601,
  serialized_end=670,
)


_ASK = _descriptor.Descriptor(
  name='Ask',
  full_name='grapevine.Ask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentence', full_name='grapevine.Ask.sentence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw_sentence', full_name='grapevine.Ask.raw_sentence', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_idx', full_name='grapevine.Ask.start_idx', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_idx', full_name='grapevine.Ask.end_idx', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prediction', full_name='grapevine.Ask.prediction', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='grapevine.Ask.confidence', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=672,
  serialized_end=793,
)


_EXTRACTION = _descriptor.Descriptor(
  name='Extraction',
  full_name='grapevine.Extraction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='grapevine.Extraction.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='grapevine.Extraction.values', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='grapevine.Extraction.confidence', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='grapevine.Extraction.model', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='grapevine.Extraction.version', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=795,
  serialized_end=888,
)

_CLASSIFICATION.fields_by_name['meta'].message_type = _META
_META.fields_by_name['sentences'].message_type = _SENTENCE
_META.fields_by_name['spamassassin_report'].message_type = _SPAMASSASSINREPORT
_META.fields_by_name['asks'].message_type = _ASK
_SPAMASSASSINREPORT.fields_by_name['quantitative_hits'].message_type = _SPAMASSASSINHIT
_SPAMASSASSINREPORT.fields_by_name['qualitative_hits'].message_type = _SPAMASSASSINHIT
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['Classification'] = _CLASSIFICATION
DESCRIPTOR.message_types_by_name['Meta'] = _META
DESCRIPTOR.message_types_by_name['Sentence'] = _SENTENCE
DESCRIPTOR.message_types_by_name['SpamAssassinReport'] = _SPAMASSASSINREPORT
DESCRIPTOR.message_types_by_name['SpamAssassinHit'] = _SPAMASSASSINHIT
DESCRIPTOR.message_types_by_name['Ask'] = _ASK
DESCRIPTOR.message_types_by_name['Extraction'] = _EXTRACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'grapevine_pb2'
  # @@protoc_insertion_point(class_scope:grapevine.Message)
  ))
_sym_db.RegisterMessage(Message)

Classification = _reflection.GeneratedProtocolMessageType('Classification', (_message.Message,), dict(
  DESCRIPTOR = _CLASSIFICATION,
  __module__ = 'grapevine_pb2'
  # @@protoc_insertion_point(class_scope:grapevine.Classification)
  ))
_sym_db.RegisterMessage(Classification)

Meta = _reflection.GeneratedProtocolMessageType('Meta', (_message.Message,), dict(
  DESCRIPTOR = _META,
  __module__ = 'grapevine_pb2'
  # @@protoc_insertion_point(class_scope:grapevine.Meta)
  ))
_sym_db.RegisterMessage(Meta)

Sentence = _reflection.GeneratedProtocolMessageType('Sentence', (_message.Message,), dict(
  DESCRIPTOR = _SENTENCE,
  __module__ = 'grapevine_pb2'
  # @@protoc_insertion_point(class_scope:grapevine.Sentence)
  ))
_sym_db.RegisterMessage(Sentence)

SpamAssassinReport = _reflection.GeneratedProtocolMessageType('SpamAssassinReport', (_message.Message,), dict(
  DESCRIPTOR = _SPAMASSASSINREPORT,
  __module__ = 'grapevine_pb2'
  # @@protoc_insertion_point(class_scope:grapevine.SpamAssassinReport)
  ))
_sym_db.RegisterMessage(SpamAssassinReport)

SpamAssassinHit = _reflection.GeneratedProtocolMessageType('SpamAssassinHit', (_message.Message,), dict(
  DESCRIPTOR = _SPAMASSASSINHIT,
  __module__ = 'grapevine_pb2'
  # @@protoc_insertion_point(class_scope:grapevine.SpamAssassinHit)
  ))
_sym_db.RegisterMessage(SpamAssassinHit)

Ask = _reflection.GeneratedProtocolMessageType('Ask', (_message.Message,), dict(
  DESCRIPTOR = _ASK,
  __module__ = 'grapevine_pb2'
  # @@protoc_insertion_point(class_scope:grapevine.Ask)
  ))
_sym_db.RegisterMessage(Ask)

Extraction = _reflection.GeneratedProtocolMessageType('Extraction', (_message.Message,), dict(
  DESCRIPTOR = _EXTRACTION,
  __module__ = 'grapevine_pb2'
  # @@protoc_insertion_point(class_scope:grapevine.Extraction)
  ))
_sym_db.RegisterMessage(Extraction)



_CLASSIFIER = _descriptor.ServiceDescriptor(
  name='Classifier',
  full_name='grapevine.Classifier',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=890,
  serialized_end=963,
  methods=[
  _descriptor.MethodDescriptor(
    name='Classify',
    full_name='grapevine.Classifier.Classify',
    index=0,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_CLASSIFICATION,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLASSIFIER)

DESCRIPTOR.services_by_name['Classifier'] = _CLASSIFIER


_EXTRACTOR = _descriptor.ServiceDescriptor(
  name='Extractor',
  full_name='grapevine.Extractor',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=965,
  serialized_end=1032,
  methods=[
  _descriptor.MethodDescriptor(
    name='Extract',
    full_name='grapevine.Extractor.Extract',
    index=0,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_EXTRACTION,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXTRACTOR)

DESCRIPTOR.services_by_name['Extractor'] = _EXTRACTOR

# @@protoc_insertion_point(module_scope)
