# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import grapevine_pb2 as grapevine__pb2


class ClassifierStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Classify = channel.unary_unary(
        '/grapevine.Classifier/Classify',
        request_serializer=grapevine__pb2.Message.SerializeToString,
        response_deserializer=grapevine__pb2.Classification.FromString,
        )


class ClassifierServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Classify(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ClassifierServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Classify': grpc.unary_unary_rpc_method_handler(
          servicer.Classify,
          request_deserializer=grapevine__pb2.Message.FromString,
          response_serializer=grapevine__pb2.Classification.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grapevine.Classifier', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class ExtractorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Extract = channel.unary_unary(
        '/grapevine.Extractor/Extract',
        request_serializer=grapevine__pb2.Message.SerializeToString,
        response_deserializer=grapevine__pb2.Extraction.FromString,
        )


class ExtractorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Extract(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ExtractorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Extract': grpc.unary_unary_rpc_method_handler(
          servicer.Extract,
          request_deserializer=grapevine__pb2.Message.FromString,
          response_serializer=grapevine__pb2.Extraction.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grapevine.Extractor', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
